#!/usr/bin/env python3
"""Generate kotlin/<contest>/BUCK files (one kotlin_library per solution file)."""

from __future__ import annotations

import pathlib

ROOT = pathlib.Path(__file__).resolve().parent.parent
KOTLIN_ROOT = ROOT / "kotlin"

HEADER = """\
# Compile-check Kotlin contest solutions (generated by scripts/gen_kotlin_buck.py).
# Each file has its own main() — one kotlin_library per source file.

"""


def target_name(path: pathlib.Path) -> str:
    return path.stem


def write_buck(contest_dir: pathlib.Path, kt_files: list[pathlib.Path]) -> None:
    lines = [HEADER]
    for kt in sorted(kt_files):
        name = target_name(kt)
        lines.append("kotlin_library(\n")
        lines.append(f'    name = "{name}",\n')
        lines.append(f'    srcs = ["{kt.name}"],\n')
        lines.append(")\n\n")
    buck = contest_dir / "BUCK"
    buck.write_text("".join(lines), encoding="utf-8")


def main() -> None:
    if not KOTLIN_ROOT.is_dir():
        raise SystemExit(f"missing {KOTLIN_ROOT}")

    contests = sorted(
        p for p in KOTLIN_ROOT.iterdir() if p.is_dir() and not p.name.startswith(".")
    )
    total = 0
    for contest in contests:
        kt_files = sorted(contest.glob("*.kt"))
        if not kt_files:
            continue
        write_buck(contest, kt_files)
        total += len(kt_files)
        print(f"wrote {contest.relative_to(ROOT)}/BUCK ({len(kt_files)} targets)")

    print(f"done: {total} kotlin_library targets in {len(contests)} contest dirs")


if __name__ == "__main__":
    main()
